### ISSUE TITLE
Recommended new model - Sport

### ISSUE THREAD

**Issue by alator21** [alator21/regular.structure#10]
A model named Sport, and some subclasses that extend it, like football,basketball,tennis etc

**Comment by MykolaKolotylo** [comment]
Hey, @alator21 Can I try to do it?

**Comment by alator21** [comment]
Hey @MykolaKolotylo, go for it :)

**Comment by MykolaKolotylo** [comment]
Hi @alator21 please take a look https://github.com/alator21/regular.structure/pull/15
