### ISSUE TITLE
Recommended new model - Food

### ISSUE THREAD

**Issue by felipedferreira** [alator21/regular.structure#11]
A model named Food, and some subclasses that extend it, like...
Dairy, Protein, Fruit, Vegetable, Grain, Legume,
would also have Animal and Human be able to eat a Food.

Would like to work on this issue please.

**Comment by alator21** [comment]
Hello @UncleFifi . A model named Food seems good. About the subclasses, maybe add only the subcategories of food like dairy,fruit,vegetable and add a property with the several nutritions like protein etc. Anyway you can go ahead and do your first attempt and we can discuss it later :)

**Comment by UncleFifi** [comment]
@alator21 Yes Dairy, Protein, Fruit, Vegetable, Grain, Legume are all subClasses of Food
and Legumes is a subClass of Vegetable
I will create multiple examples of each

**Comment by UncleFifi** [comment]
I have made my commit. Would you kindly be able to review commit and let me know if you would like something else?
